/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.TaiLieu;
import Service.TaiLieuService;
import javax.swing.ComboBoxModel;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Toàn
 */
public class themTaiLieu extends javax.swing.JFrame {

    /**
     * Creates new form themTaiLieu
     */
    DefaultTableModel defaultTableModel;
    TaiLieuService taiLieuservice;

    public themTaiLieu() {
        initComponents();
        addTheLoai.removeAllItems();
        taiLieuservice = new TaiLieuService();
        setTimKiemData();
        addSoLg.setModel(new SpinnerNumberModel(1, 1, 1000000, 1));
        addSoTrang.setModel(new SpinnerNumberModel(1, 1, 10000, 1));
        addSoPhatHanh.setModel(new SpinnerNumberModel(1, 1, 100, 1));
        setNgayPhatHanh();

    }

    private void anDanhMuc() {

        addTenTG.setVisible(false);
        addTenTGField.setVisible(false);
        addSoTrangField.setVisible(false);
        addSoTrang.setVisible(false);

        addSoPhatHanh.setVisible(false);
        addSoPhatHanhField.setVisible(false);
        addThang.setVisible(false);
        addThangField1.setVisible(false);

        addNgay.setVisible(false);
        addNgayField.setVisible(false);

    }

    private void setTimKiemData() {

        addTheLoai.addItem("Chọn thể loại");
        for (String theLoai : taiLieuservice.getTheLoai()) {
            addTheLoai.addItem(theLoai);
        }
    }

    private void setNgayPhatHanh() {

        addNgay.removeAllItems();
        for (int i = 1; i <= taiLieuservice.getDate(Integer.valueOf(addThang.getSelectedItem().toString())); i++) {
            addNgay.addItem(String.valueOf(i));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        timKiemList = new javax.swing.JComboBox<>();
        addThangField = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        addTheLoaiTextField = new javax.swing.JLabel();
        addTheLoai = new javax.swing.JComboBox<>();
        addNXBField = new javax.swing.JLabel();
        addSoLgField = new javax.swing.JLabel();
        addNXB = new javax.swing.JTextField();
        addSoLg = new javax.swing.JSpinner();
        addTenTGField = new javax.swing.JLabel();
        addTenTG = new javax.swing.JTextField();
        addSoPhatHanhField = new javax.swing.JLabel();
        addSoTrang = new javax.swing.JSpinner();
        addBT = new javax.swing.JButton();
        addSoTrangField = new javax.swing.JLabel();
        addNgayField = new javax.swing.JLabel();
        addSoPhatHanh = new javax.swing.JSpinner();
        addThang = new javax.swing.JComboBox<>();
        addNgay = new javax.swing.JComboBox<>();
        backBT = new javax.swing.JButton();
        addThangField1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        timKiemList.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                timKiemListItemStateChanged(evt);
            }
        });

        addThangField.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        addThangField.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        addThangField.setText("Tháng phát hành :");

        jFormattedTextField1.setText("jFormattedTextField1");

        jButton3.setText("Thoát");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Thêm Tài Liệu");

        addTheLoaiTextField.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        addTheLoaiTextField.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        addTheLoaiTextField.setText("Loại tài liệu :");

        addTheLoai.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                addTheLoaiItemStateChanged(evt);
            }
        });
        addTheLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTheLoaiActionPerformed(evt);
            }
        });

        addNXBField.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        addNXBField.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        addNXBField.setText("Tên NXB :");

        addSoLgField.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        addSoLgField.setText("Số Bản Phát Hành :");

        addNXB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNXBActionPerformed(evt);
            }
        });

        addSoLg.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        addSoLg.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addSoLg.setPreferredSize(new java.awt.Dimension(30, 30));
        addSoLg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addSoLgMouseExited(evt);
            }
        });

        addTenTGField.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        addTenTGField.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        addTenTGField.setText("Tên Tác Giả :");

        addSoPhatHanhField.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        addSoPhatHanhField.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        addSoPhatHanhField.setText("Số phát hành :");

        addBT.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        addBT.setText("Thêm");
        addBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBTActionPerformed(evt);
            }
        });

        addSoTrangField.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        addSoTrangField.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        addSoTrangField.setText("Số trang :");

        addNgayField.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        addNgayField.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        addNgayField.setText("Ngày phát hành :");

        addThang.setEditable(true);
        addThang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        addThang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addThangActionPerformed(evt);
            }
        });

        addNgay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNgayActionPerformed(evt);
            }
        });

        backBT.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        backBT.setText("TRỜ VỀ");
        backBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBTActionPerformed(evt);
            }
        });

        addThangField1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        addThangField1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        addThangField1.setText("Tháng phát hành :");

        jButton4.setText("Thoát");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(addBT, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(addNgayField, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(addSoPhatHanhField, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(addSoTrangField, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(addTenTGField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(addSoLgField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(addNXBField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(addTheLoaiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(addThangField1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(addTenTG, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addSoLg, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addTheLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addNXB, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addSoTrang, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(addThang, javax.swing.GroupLayout.Alignment.LEADING, 0, 98, Short.MAX_VALUE)
                                        .addComponent(addNgay, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(addSoPhatHanh, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backBT, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBT, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addTheLoaiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addTheLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addNXB, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addNXBField, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addSoLgField, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addSoLg, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addTenTGField, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addTenTG, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addSoTrang, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addSoTrangField, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addSoPhatHanh, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addSoPhatHanhField, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addThang, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addThangField1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addNgayField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBT, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void timKiemListItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_timKiemListItemStateChanged
        // TODO add your handling code here:
        //day;


    }//GEN-LAST:event_timKiemListItemStateChanged

    private void addNXBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNXBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addNXBActionPerformed

    private void addBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBTActionPerformed
        if (addNXB.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Nhập tên NXB");
        } else if (addTheLoai.getSelectedItem().equals("Chọn thể loại")) {
            JOptionPane.showMessageDialog(this, "Vui lòng Chọn Thể Loại");
        } else if (addTheLoai.getSelectedItem().equals("Sách") && addTenTG.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng Chọn Tên Tác Giả");
        } else {

            if (addTheLoai.getSelectedItem().equals("Sách")) {

            }

            switch (addTheLoai.getSelectedItem().toString()) {
                case "Sách":
                    if (taiLieuservice.addTaiLieu(addTheLoai.getSelectedItem().toString(),
                            addNXB.getText(),
                            Integer.valueOf(addSoLg.getValue().toString()),
                            addTenTG.getText(),
                            Integer.valueOf(addSoTrang.getValue().toString()),
                            0,
                            0,
                            0)
                            == 0) {
                        JOptionPane.showMessageDialog(this, "Thêm thất bại! Vui lòng thử lại.", "Thông báo", JOptionPane.ERROR_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(this, "Thêm Thành Công");
                        new DsTaiLieu().setVisible(true);
                        this.dispose();
                    }
                    break;
                case "Tạp Chí":
                    if (taiLieuservice.addTaiLieu(
                            addTheLoai.getSelectedItem().toString(),
                            addNXB.getText(),
                            Integer.valueOf(addSoLg.getValue().toString()),
                            null,
                            0,
                            Integer.valueOf(addSoPhatHanh.getValue().toString()),
                            Integer.valueOf(addThang.getSelectedItem().toString()),
                            0
                    ) == 0) {
                        JOptionPane.showMessageDialog(this, "Thêm thất bại! Vui lòng thử lại.", "Thông báo", JOptionPane.ERROR_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(this, "Thêm Thành Công");
                        new DsTaiLieu().setVisible(true);
                        this.dispose();
                    }
                    break;
                case "Báo":
                    
                    if (taiLieuservice.addTaiLieu(addTheLoai.getSelectedItem().toString(),
                    addNXB.getText(),
                    Integer.valueOf(addSoLg.getValue().toString()),
                    null,
                    0,
                    0,
                    Integer.valueOf(addThang.getSelectedItem().toString()),
                    Integer.valueOf(addNgay.getSelectedItem().toString())
                      ) == 0) {
                        JOptionPane.showMessageDialog(this, "Thêm thất bại! Vui lòng thử lại.", "Thông báo", JOptionPane.ERROR_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(this, "Thêm Thành Công");
                        new DsTaiLieu().setVisible(true);
                        this.dispose();
                    }                  
                    break;
            }

//            if (taiLieuservice.addTaiLieu(addTheLoai.getSelectedItem().toString(),
//                    addNXB.getText(),
//                    Integer.valueOf(addSoLg.getValue().toString()),
//                    addTenTG.getText(),
//                    Integer.valueOf(addSoTrang.getValue().toString()),
//                    Integer.valueOf(addSoPhatHanh.getValue().toString()),
//                    Integer.valueOf(addThang.getSelectedItem().toString()),
//                    Integer.valueOf(addNgay.getSelectedItem().toString())
//            ) == 0) {
//                JOptionPane.showMessageDialog(this, "Thêm thất bại! Vui lòng thử lại.", "Thông báo", JOptionPane.ERROR_MESSAGE);
//            } else {
//                JOptionPane.showMessageDialog(this, "Thêm Thành Công");
//                new DsTaiLieu().setVisible(true);
//                this.dispose();
//            }

        }
    }//GEN-LAST:event_addBTActionPerformed

    private void addSoLgMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addSoLgMouseExited
        // TODO add your handling code here:

    }//GEN-LAST:event_addSoLgMouseExited

    private void addNgayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNgayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addNgayActionPerformed

    private void addThangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addThangActionPerformed
        // TODO add your handling code here:
        setNgayPhatHanh();
    }//GEN-LAST:event_addThangActionPerformed

    private void addTheLoaiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_addTheLoaiItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_addTheLoaiItemStateChanged

    private void addTheLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTheLoaiActionPerformed
        // TODO add your handling code here:

        anDanhMuc();
        switch (addTheLoai.getSelectedItem().toString()) {
            case "Sách":
                addTenTG.setVisible(true);
                addTenTGField.setVisible(true);
                addSoTrangField.setVisible(true);
                addSoTrang.setVisible(true);
                break;
            case "Tạp Chí":
                addSoPhatHanh.setVisible(true);
                addSoPhatHanhField.setVisible(true);
                addThang.setVisible(true);
                addThangField1.setVisible(true);
                break;
            case "Báo":
                addThang.setVisible(true);
                addThangField1.setVisible(true);
                addNgay.setVisible(true);
                addNgayField.setVisible(true);
                break;

        }
    }//GEN-LAST:event_addTheLoaiActionPerformed

    private void backBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBTActionPerformed
        // TODO add your handling code here:
        new DsTaiLieu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBTActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(themTaiLieu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(themTaiLieu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(themTaiLieu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(themTaiLieu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new themTaiLieu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBT;
    private javax.swing.JTextField addNXB;
    private javax.swing.JLabel addNXBField;
    private javax.swing.JComboBox<String> addNgay;
    private javax.swing.JLabel addNgayField;
    private javax.swing.JSpinner addSoLg;
    private javax.swing.JLabel addSoLgField;
    private javax.swing.JSpinner addSoPhatHanh;
    private javax.swing.JLabel addSoPhatHanhField;
    private javax.swing.JSpinner addSoTrang;
    private javax.swing.JLabel addSoTrangField;
    private javax.swing.JTextField addTenTG;
    private javax.swing.JLabel addTenTGField;
    private javax.swing.JComboBox<String> addThang;
    private javax.swing.JLabel addThangField;
    private javax.swing.JLabel addThangField1;
    private javax.swing.JComboBox<String> addTheLoai;
    private javax.swing.JLabel addTheLoaiTextField;
    private javax.swing.JButton backBT;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JComboBox<String> timKiemList;
    // End of variables declaration//GEN-END:variables
}
